---
title: "Untitled"
author: "Alex"
date: "2/16/2023"
output: html_document
---

```{r}
library(FRASER)
library(data.table)
set.seed(100)

```


```{r, import arguments}
args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

```

```{r, show arguments}
print(data_directory)
print(output_directory)


```

```{r}
fds <- loadFraserDataSet(
                  dir = 
                paste0(data_directory,"/Geuvadis/Fraser"),
                  name = "Geuvadis_filtered_counts")

fds <- saveFraserDataSet(fds = fds, 
                  dir = 
                paste0(output_directory,"/Fraser"),
                  name = "Geuvadis_PCA_BB_Decoder_results")

fds <- loadFraserDataSet(
                  dir = 
                paste0(output_directory,"/Fraser"),
                  name = "Geuvadis_PCA_BB_Decoder_results")


fds_hyperparameters <- loadFraserDataSet(
                  dir = 
                paste0(output_directory,"/Fraser"),
                  name = "Geuvadis_optimal_hyperparameters_PCA")


```




```{r}

start_time_analysis <- Sys.time()


fds <- fit(fds,
           type = c("psi3"),
           q = bestQ(fds, type = "psi3"),
              implementation = "PCA-BB-Decoder",
              BPPARAM = MulticoreParam(1))

fds <- fit(fds,
           type = c("psi5"),
           q = bestQ(fds, type = "psi5"),
              implementation = "PCA-BB-Decoder",
              BPPARAM = MulticoreParam(1))

fds <- calculatePvalues(fds = fds,
                        type = c("psi3"),
                        implementation = "PCA-BB-Decoder",
                        BPPARAM = MulticoreParam(1))

fds <- calculatePvalues(fds = fds,
                        type = c("psi5"),
                        implementation = "PCA-BB-Decoder",
                        BPPARAM = MulticoreParam(1))
end_time <- Sys.time()

time_analysis <- end_time - start_time_analysis

saveRDS(object = time_analysis, 
        file = paste0(output_directory,"/Time_analysis_Fraser_PCA_BB_Decoder.RDS"))


fds <- saveFraserDataSet(fds = fds, 
                  dir = 
                paste0(output_directory,"/Fraser"),
                  name = "Geuvadis_PCA_BB_Decoder_results")
```

