---
title: "Untitled"
author: "Alex"
date: "2/22/2023"
output: html_document
---

```{r}
library(ASpli)
library(GenomicFeatures)
library(lubridate)
library(BiocParallel)
library(SummarizedExperiment)
library(dplyr)
library(pracma)
library(PRROC)
library(FRASER)
library(data.table)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
set.seed(100)
```

```{r, import arguments}
args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

```

```{r, show arguments}
print(output_directory)
print(data_directory)
print(function_directory)


```


```{r}
source(paste0(function_directory,
              "/fitRUVMD-aberrant-splicing.R"))
source(paste0(function_directory, 
              "/Accessors.R"))

```


```{r}
fds <- loadFraserDataSet(
                  dir = paste0(data_directory,"/Kremer/Fraser"),
                         name = "Outliers_injection_jaccard")

```




```{r}
jcounts <- as.data.frame(counts(fds))
sample_names <- colnames(jcounts)
jcounts$locus <- rowRanges(fds)$hgnc_symbol

data <- SummarizedExperiment(metadata = list("binCounts" = jcounts),
                             colData = list("Names" = sample_names))

```


```{r}

filtered_junctioncounts <- FilterBinCounts(data)
seJunctionCounts <- getCountsSplicing(filtered_junctioncounts, type = "bin")
seJunctionCounts <- seJunctionCounts[!(is.na(rowData(seJunctionCounts)$locus)),]
seJunctionCounts <- OffsetSplicing(seJunctionCounts)

filter <- filterByExpr(seJunctionCounts,
                            min.count = 10,
                            min.total.count = 15,
                            large.n = 10,
                            min.prop = 0.7)

seJunctionCounts <- seJunctionCounts[filter, ]
metadata(seJunctionCounts)$design <- ~1



```


```{r}

seFindEncDim <- findEncodingDimRUVSplicing(seJunctionCounts,
                                  dimensions = seq(1,20,1),
                                  freq = 10^-2,
                                  BPPARAM = MulticoreParam(workers = 1))




saveRDS(object = seFindEncDim, 
        file = paste0(output_directory,"/seOptimalHyperparameters_bins_Kremer_jaccard_outliers.RDS"))
```


```{r}

seFit <- fitRUVMD(se = seFindEncDim, 
                  dimensions = metadata(seFindEncDim)$optimalEncDim)


saveRDS(object = seFit, 
        file = paste0(output_directory,"/seFit_bins_Kremer_jaccard_outliers.RDS"))
```








