---
title: "Untitled"
author: "Alex"
date: "2/22/2023"
output: html_document
---

```{r}
library(FRASER)
library(data.table)
```


```{r, import arguments}
args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

```

```{r}
print(data_directory)
```


```{r}
#adapted from FRASER:::extractSpliceSiteCoordinates

extractSpliceSiteCoordinates <- function (junctions, strandspecific = F) 
{
    if (strandspecific >= 1L) {
        spliceSiteCoords <- unlist(GRangesList(FRASER:::extractSpliceSiteCoordsPerStrand(junctions, 
            "+"), FRASER:::extractSpliceSiteCoordsPerStrand(junctions, 
            "-")))
    }
    else {
        strand(junctions) <- "*"
        spliceSiteCoords <- FRASER:::extractSpliceSiteCoordsPerStrand(junctions, 
            "*")
    }
    return(unique(sort(spliceSiteCoords)))
}
```


```{r}
sampleTable <- fread(paste0(data_directory, 
                            "/Kremer/kremer--hg19--gencode34/sampleAnnotation.tsv"))
jcounts <- fread(paste0(data_directory, 
                        "/Kremer/kremer--hg19--gencode34/k_j_counts.tsv.gz"))
nonsplitreads <- fread(paste0(data_directory,
                              "/Kremer/kremer--hg19--gencode34/k_theta_counts.tsv.gz"))




gr_jcounts <- FRASER:::annotateSpliceSite(GRanges(jcounts))
splicesites <- extractSpliceSiteCoordinates(gr_jcounts,strandspecific = F)

gr_nonsplit_reads <- GRanges(nonsplitreads)
gr_nonsplit_reads$spliceSiteID <- splicesites$spliceSiteID[match(gr_nonsplit_reads@ranges,splicesites@ranges, 
                                                                 nomatch = 0)]
gr_nonsplit_reads$type <- splicesites$type[match(gr_nonsplit_reads@ranges,splicesites@ranges, nomatch = 0)]

sampleTable$sampleID <- sampleTable$RNA_ID
sampleTable <- sampleTable[match(colnames(jcounts),sampleTable$sampleID, nomatch = 0)]
sampleTable$sampleID[1:33] <- paste0("X",sampleTable$sampleID[1:33])


fds <- FraserDataSet(colData=sampleTable, 
                     junctions = as.data.frame(gr_jcounts),
                     spliceSites=as.data.frame(gr_nonsplit_reads))
```


```{r}

saveFraserDataSet(fds = fds, 
                  dir = paste0(data_directory, 
                               "/Kremer/Fraser"), 
                           name = "transformed_counts")

saveFraserDataSet(fds = fds, 
                  dir = paste0(data_directory, 
                               "/Kremer/Fraser"), 
                           name = "filtered_counts")
```



```{r}
fds <- loadFraserDataSet(dir = paste0(data_directory, 
                               "/Kremer/Fraser"), name = "filtered_counts")
```


```{r}
fds <- calculatePSIValues(fds, BPPARAM = MulticoreParam(1))
fds <- filterExpressionAndVariability(fds, BPPARAM = MulticoreParam(1))

fds <- fds[mcols(fds,type ="j")[,"passed"],]


fds_original <- fds
fds_psi3_outliers <- fds
fds_psi5_outliers <- fds


saveFraserDataSet(fds = fds_original, 
                  dir = paste0(data_directory, 
                               "/Kremer/Fraser"), name = "filtered_counts")

saveFraserDataSet(fds = fds_psi3_outliers, 
                  dir = paste0(data_directory, 
                               "/Kremer/Fraser"), name = "filtered_counts_psi3")

saveFraserDataSet(fds = fds_psi5_outliers, 
                  dir = paste0(data_directory, 
                               "/Kremer/Fraser"), name = "filtered_counts_psi5")


```


```{r}

fds_psi5_outliers <- loadFraserDataSet(dir = paste0(data_directory, 
                               "/Kremer/Fraser"), name = "filtered_counts_psi5")
set.seed(100)
fds_psi5_outliers <- injectOutliers(fds_psi5_outliers, 
                               type = c("psi5"), 
                               freq = 0.001, 
                               minDpsi = 0.2,
                               minCoverage = 2,
                               deltaDistr = "uniformDistr",
                               BPPARAM = MulticoreParam(1)) 

saveFraserDataSet(fds = fds_psi5_outliers, dir = 
                      paste0(data_directory, 
                               "/Kremer/Fraser"), 
                  name = "Outliers_injection_psi_5")
```




```{r}
fds_psi3_outliers <- loadFraserDataSet(dir = paste0(data_directory, 
                               "/Kremer/Fraser"), name = "filtered_counts_psi3")
set.seed(100)
fds_psi3_outliers <- injectOutliers(fds_psi3_outliers, 
                               type = c("psi3"), 
                               freq = 0.001, 
                               minDpsi = 0.2,
                               minCoverage = 2,
                               deltaDistr = "uniformDistr",
                               BPPARAM = MulticoreParam(1)) 

saveFraserDataSet(fds = fds_psi3_outliers, dir = 
                      paste0(data_directory, 
                               "/Kremer/Fraser"), 
                  name = "Outliers_injection_psi_3")
```
