---
author: "Alex"
date: "9/22/2022"
output: html_document
---
```{r, libraries}
library(ggplot2)
library(dplyr)
library(OUTRIDER)
library(magrittr)
library(patchwork)
library(cowplot)
library(ggpubr)
```


```{r, import arguments}
 args <- (commandArgs(trailingOnly = TRUE))
 for (i in 1:length(args)) {
   eval(parse(text = args[[i]]))
}
 
```
 
```{r}
 print(data_directory)
 print(output_directory)
```

```{r}
rds_GTEx_RUV='/RUV_Analysis_GTEx_Marginal_outliers.RDS'
rds_GTEx_RUV_threshold='/RUV_optimalThreshold_Analysis_GTEx_Marginal_outliers.RDS'
rds_GTEx_RUV_edgeR='/RUV_edgeR_Analysis_GTEx_Marginal_outliers.RDS'
rds_GTEx_Outrider_Autoencoder_part_1='/Outrider_autoencoder_Analysis_GTEx_Marginal_outliers_in_parts_1.RDS'
rds_GTEx_Outrider_Autoencoder_part_2='/Outrider_autoencoder_Analysis_GTEx_Marginal_outliers_in_parts_2.RDS'
rds_GTEx_Outrider_PCA='/Outrider_PCA_Analysis_GTEx_Marginal_outliers.RDS'
Outsingle <- '/GTEx_counts_Marginal_Outliers_pandasdf-fzse-zs-svd-optht-zs.csv'

time_Outsingle <- '/time_OutSingle.txt'

```


```{r, import functions}
AUC_calculation <- function(se){
  
  require(precrec)
  
  auc_matrix <- matrix(NA, ncol = ncol(se), nrow = 1)
    
    for(i in c(1:ncol(se))){
    scores <-  -c(unlist(assays(se)$pValue[,i]))
    labels <-  c(unlist(abs(assays(se)$Outliers[,i])))
    msmdat_simulation <- mmdata(c(join_scores(scores,chklen=F)),
                                c(join_labels(labels,chklen=F)))
    mscurves_simulation <- evalmod(msmdat_simulation)
    auc_matrix[,i] <- subset(auc(mscurves_simulation),curvetypes == "PRC")$aucs
      
   }

  
  return(auc_matrix)
  
  

}
```


```{r}
rds_GTEx_RUV <- readRDS(file = paste0(data_directory,rds_GTEx_RUV))
rds_GTEx_RUV_threshold <- readRDS(file = paste0(data_directory,rds_GTEx_RUV_threshold))
rds_GTEx_Outrider_Autoencoder_part_1 <- readRDS(file = paste0(data_directory,rds_GTEx_Outrider_Autoencoder_part_1))
rds_GTEx_Outrider_Autoencoder_part_2 <- readRDS(file = paste0(data_directory,rds_GTEx_Outrider_Autoencoder_part_2))
rds_GTEx_Outrider_PCA <- readRDS(file = paste0(data_directory,rds_GTEx_Outrider_PCA))
rds_GTEx_RUV_edgeR <- readRDS(file = paste0(data_directory,rds_GTEx_RUV_edgeR))
Outsingle <- read.delim(paste0(data_directory,Outsingle))

read.delim(paste0(data_directory,time_Outsingle),header = F)
```

```{r}
AutoencoderEncDimTable <- rbind(metadata(rds_GTEx_Outrider_Autoencoder_part_1)$encDimTable,
                                metadata(rds_GTEx_Outrider_Autoencoder_part_2)$encDimTable)

max_index <- which.max(AutoencoderEncDimTable$evaluationLoss)
max_dimension <- AutoencoderEncDimTable$encodingDimension[max_index]

if(max_dimension <= 50){
  rds_GTEx_Outrider_Autoencoder <- rds_GTEx_Outrider_Autoencoder_part_1
  metadata(rds_GTEx_Outrider_Autoencoder)$time <- metadata(rds_GTEx_Outrider_Autoencoder_part_1)$time_hyperparam + 
                                                  metadata(rds_GTEx_Outrider_Autoencoder_part_2)$time_hyperparam + 
                                                  metadata(rds_GTEx_Outrider_Autoencoder_part_1)$time_analysis
} else {
  rds_GTEx_Outrider_Autoencoder <- rds_GTEx_Outrider_Autoencoder_part_2
  metadata(rds_GTEx_Outrider_Autoencoder)$time <- metadata(rds_GTEx_Outrider_Autoencoder_part_1)$time_hyperparam + 
                                                  metadata(rds_GTEx_Outrider_Autoencoder_part_2)$time_hyperparam + 
                                                  metadata(rds_GTEx_Outrider_Autoencoder_part_2)$time_analysis
}
```


```{r,auc calculation}
list_rds <- list(rds_GTEx_RUV,
                 rds_GTEx_RUV_threshold,
     rds_GTEx_Outrider_Autoencoder,
     rds_GTEx_Outrider_PCA
)

list_auc <- lapply(list_rds, AUC_calculation)


library(magrittr)

list_rds_time <- list(rds_GTEx_RUV,
                      rds_GTEx_RUV_threshold,
     rds_GTEx_RUV_edgeR,
     rds_GTEx_Outrider_Autoencoder,
     rds_GTEx_Outrider_PCA
)

list_time <- list_rds_time %>% lapply(. %>% metadata) %>% lapply(. %>% .["time"]) %>% unlist
```


```{r}
auc_matrix_Outsingle <- matrix(NA, ncol = ncol(Outsingle), nrow = 1)
    
    for(i in c(1:ncol(Outsingle))){
    scores <-  abs(unlist(Outsingle[,i]))
    labels <-  c(unlist(abs(assays(rds_GTEx_RUV)$Outliers[,i])))
    msmdat_simulation <- mmdata(c(join_scores(scores,chklen=F)),
                                c(join_labels(labels,chklen=F)))
    mscurves_simulation <- evalmod(msmdat_simulation)
    auc_matrix_Outsingle[,i] <- subset(auc(mscurves_simulation),curvetypes == "PRC")$aucs
      
   }
```

```{r}
df_performance <- data.frame("aucs" = c(unlist(list_auc),c(unlist(auc_matrix_Outsingle))),
                             "method" = c(rep(c("saseR hyperparameters","saseR",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA", "OutSingle"),
                                  each = 249)))

df_performance$method <- factor(df_performance$method,levels = c("saseR hyperparameters","saseR", "OutSingle",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA"))
```


```{r}
df_time <- data.frame("time" = c(list_time/3600,(93.179+203.839)/3600), 
                      method = c("saseR hyperparameters","saseR",
                                     "saseR edgeR",
                                     "OUTRIDER-Autoencoder", 
                                     "OUTRIDER-PCA","OutSingle"))
df_time$method <- factor(df_time$method,levels = c("saseR","saseR hyperparameters", "OutSingle",
                                                   "saseR edgeR",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA"))

```


```{r}
bp.vals <- function(x, probs=c(0.05, 0.25, 0.5,0.75, .95)) {
  r <- quantile(x, probs=probs , na.rm=TRUE)
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}
```

# Figure 1 Results

```{r}
scores <- join_scores(
                      -c(unlist(assays(rds_GTEx_RUV_threshold)$pValue)),
                      abs(unlist(Outsingle)),
                      -c(unlist(assays(rds_GTEx_Outrider_Autoencoder)$pValue)),
                      -c(unlist(assays(rds_GTEx_Outrider_PCA)$pValue)),
                      -c(unlist(assays(rds_GTEx_RUV)$pValue)),
                      chklen = F)

labels <- join_labels(
                      c(unlist(abs(assays(rds_GTEx_RUV_threshold)$Outliers))),
                      c(unlist(abs(assays(rds_GTEx_RUV_threshold)$Outliers))),
                      c(unlist(abs(assays(rds_GTEx_Outrider_Autoencoder)$Outliers))),
                      c(unlist(abs(assays(rds_GTEx_Outrider_PCA)$Outliers))),
                      c(unlist(abs(assays(rds_GTEx_RUV)$Outliers))),
                      chklen = F)


msmdat_simulation <- mmdata(scores,
                            labels,
                            modnames =
                              c("saseR","OutSingle","OUTRIDER-Autoencoder","OUTRIDER-PCA", 
                                "saseR hyperparameters"),
                            dsids = c(1:5))
mscurves_simulation <- evalmod(msmdat_simulation)
df_pr <- as.data.frame(mscurves_simulation)
df_pr$modname <- factor(df_pr$modname,levels = c("saseR","saseR hyperparameters", "OutSingle",
                                                   "saseR edgeR",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA"))


```


```{r}
plot_1 <- ggplot(data = df_performance %>% filter(method %in% c("saseR", "OutSingle",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA")) ,aes(x = method, y = aucs, col = method))  + stat_summary(fun.data = bp.vals, geom="boxplot") + geom_jitter(size = 0.2)  + scale_color_manual(values = c("saseR" = "#E69F00", "OutSingle" = "#56B4E9","OUTRIDER-Autoencoder"="#0072B2", "OUTRIDER-PCA"= "#009E73")) + ylab("Area under the curve per sample") + theme_bw() + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ylim(c(0,1.0001)) + theme(legend.position = "none")+
  theme(axis.text=element_text(size=10), axis.title=element_text(size=12)) 
print(plot_1)

```


```{r}
#time_labels <- c("1.6 h","2.0 min","43.3 h","28.7 h","1.0 h", "5.0 min")
time_labels <- c("2 min","28.7 h","1.0 h", "5 min")

plot_2 <- ggplot(data = df_time %>% filter(method %in% c("saseR",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA", "OutSingle")), aes(y = time*60, x= method,fill = method)) + geom_bar(stat="identity", alpha =0.8) + scale_fill_manual(values = c("saseR" = "#E69F00", "OutSingle" = "#56B4E9", "OUTRIDER-Autoencoder"="#0072B2", "OUTRIDER-PCA"= "#009E73"))  + ylab("Computational time (minutes)") + scale_y_continuous(trans='log10') + 
  theme(legend.title = element_blank()) + theme_bw() + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ theme(legend.text=element_text(size=10)) + 
  theme(axis.text=element_text(size=10), axis.title=element_text(size=12)) + geom_text(aes(label=time_labels), position=position_dodge(width=0.9), vjust=-0.25, size = 4)+theme(legend.title = element_blank()) + theme(legend.position = "none") + coord_cartesian(ylim = c(1,10000))


print(plot_2)
```



```{r}

plot_3 <- ggplot(data = df_pr%>% filter(type == "PRC" & (modname %in% c("saseR",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA", "OutSingle"))), aes(x = x, y = y, col = modname)) + geom_line() + ggtitle(label = "") + ylab("Precision")  + xlab("Recall") + theme_bw() + 
  theme(axis.text=element_text(size=10), axis.title=element_text(size=12))  + scale_color_manual(values = c("saseR" = "#E69F00", "OutSingle" = "#56B4E9", "OUTRIDER-Autoencoder"="#0072B2", "OUTRIDER-PCA"= "#009E73"))+ 
  theme( legend.title = element_blank(),legend.position = "bottom", 
         legend.text = element_text(size = 12))
plot_3
```

```{r}
legend <- get_legend(plot_3)
prow <- plot_grid(plot_1 + theme(legend.position = "none"), plot_3 + theme(legend.position = "none"),
                  plot_2 + theme(legend.position = "none"), labels = c("A","B","C"), ncol = 3,
                  rel_heights = c(1,1,1), align = "h")

```

```{r}
Figure_1 <- plot_grid(prow,legend,ncol = 1, rel_heights= c(1,0.1))
Figure_1
```






```{r}
ggsave(paste0(output_directory,"/Figure-2.png"), Figure_1, 
       device = "png", width = 9, height = 4.5, dpi = 300)
ggsave(paste0(output_directory,"/Figure-2.eps"), Figure_1, 
       device = cairo_ps, width = 9, height = 4.5, dpi = 300)
ggsave(paste0(output_directory,"/Figure-2.pdf"), Figure_1, 
       device = "pdf", width = 9, height = 4.5, dpi = 300)

```




```{r}
plot_1 <- ggplot(data = df_performance %>% filter(method %in% c("saseR hyperparameters", "OutSingle",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA")) ,aes(x = method, y = aucs, col = method))  + stat_summary(fun.data = bp.vals, geom="boxplot") + geom_jitter(size = 0.2)  + scale_color_manual(values = c("saseR hyperparameters" = "#E69F00", "OutSingle" = "#56B4E9","OUTRIDER-Autoencoder"="#0072B2", "OUTRIDER-PCA"= "#009E73")) + ylab("Area under the curve per sample") + theme_bw() + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + ylim(c(0,1.0001)) + theme(legend.position = "none")+
  theme(axis.text=element_text(size=10), axis.title=element_text(size=12)) 
print(plot_1)

```


```{r}
time_labels <- c("1.6 h","28.7 h","1.0 h", "5 min")

plot_2 <- ggplot(data = df_time %>% filter(method %in% c("saseR hyperparameters",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA", "OutSingle")), aes(y = time*60, x= method,fill = method)) + geom_bar(stat="identity", alpha =0.8) + scale_fill_manual(values = c("saseR hyperparameters" = "#E69F00", "OutSingle" = "#56B4E9", "OUTRIDER-Autoencoder"="#0072B2", "OUTRIDER-PCA"= "#009E73"))  + ylab("Computational time (minutes)") + scale_y_continuous(trans='log10') + 
  theme(legend.title = element_blank()) + theme_bw() + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ theme(legend.text=element_text(size=10)) + 
  theme(axis.text=element_text(size=10), axis.title=element_text(size=12)) + geom_text(aes(label=time_labels), position=position_dodge(width=0.9), vjust=-0.25, size = 4)+theme(legend.title = element_blank()) + theme(legend.position = "none") + coord_cartesian(ylim = c(1,10000))


print(plot_2)
```



```{r}

plot_3 <- ggplot(data = df_pr%>% filter(type == "PRC" & (modname %in% c("saseR hyperparameters",
                                    "OUTRIDER-Autoencoder", 
                                    "OUTRIDER-PCA", "OutSingle"))), aes(x = x, y = y, col = modname)) + geom_line() + ggtitle(label = "") + ylab("Precision")  + xlab("Recall") + theme_bw() + 
  theme(axis.text=element_text(size=10), axis.title=element_text(size=12))  + scale_color_manual(values = c("saseR hyperparameters" = "#E69F00", "OutSingle" = "#56B4E9", "OUTRIDER-Autoencoder"="#0072B2", "OUTRIDER-PCA"= "#009E73"))+ 
  theme( legend.title = element_blank(),legend.position = "bottom", 
         legend.text = element_text(size = 12))
plot_3
```

```{r}
legend <- get_legend(plot_3)
prow <- plot_grid(plot_1 + theme(legend.position = "none"), plot_3 + theme(legend.position = "none"),
                  plot_2 + theme(legend.position = "none"), labels = c("A","B","C"), ncol = 3,
                  rel_heights = c(1,1,1), align = "h")

```

```{r}
Figure_1 <- plot_grid(prow,legend,ncol = 1, rel_heights= c(1,0.1))
Figure_1
```


```{r}
ggsave(paste0(output_directory,"/Supplementary-Figure-2.png"), Figure_1, 
       device = "png", width = 9, height = 4.5, dpi = 300)
ggsave(paste0(output_directory,"/Supplementary-Figure-2.eps"), Figure_1, 
       device = cairo_ps, width = 9, height = 4.5, dpi = 300)
ggsave(paste0(output_directory,"/Supplementary-Figure-2.pdf"), Figure_1, 
       device = "pdf", width = 9, height = 4.5, dpi = 300)

```


